In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D
import numpy as np
from tensorflow.keras.preprocessing import image

Load Data

In [3]:
train_data = ImageDataGenerator(rescale = 1./255,
                                shear_range = 0.2,
                                zoom_range = 0.2,
                                horizontal_flip = True)

Train dataset

In [7]:
training_set = train_data.flow_from_directory('../input/cotton-disease-dataset/Cotton Disease/train',
                                                target_size = (64,64),
                                                batch_size = 32,
                                                class_mode = 'categorical')

Found 1951 images belonging to 4 classes.


Test dataset

In [8]:
test_data = ImageDataGenerator(rescale=1./255)

In [10]:
test_set = test_data.flow_from_directory('../input/cotton-disease-dataset/Cotton Disease/test',
                                        target_size = (64,64),
                                        batch_size = 32,
                                        class_mode = 'categorical')

Found 106 images belonging to 4 classes.


Building CNN

In [13]:
#Initialise
cnn = tf.keras.models.Sequential()

# Step 1 - Convolution
cnn.add(tf.keras.layers.Conv2D(filters=32, padding = 'same', kernel_size = 3, activation = "relu", input_shape=[64,64,3]))

#Step 2 - Pooling
cnn.add(tf.keras.layers.MaxPool2D(strides = 2 , pool_size = 2))

#Add Second Convolutional Layer
cnn.add(tf.keras.layers.Conv2D(filters = 32, padding = 'same', kernel_size = 3,activation = 'relu' ))
cnn.add(tf.keras.layers.MaxPool2D(strides = 2, pool_size = 2))

#Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

#Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units = 128, activation = 'relu'))

#Step 5 - Output Layers
cnn.add(tf.keras.layers.Dense(units = 4, activation = 'softmax'))

In [14]:
cnn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 8192)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1048704   
_________________________________________________________________
dense_1 (Dense)              (None, 4)                

Compile CNN

In [17]:
cnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Training the CNN on the Training set and evaluating it on the Test set
cnn.fit(x = training_set, validation_data = test_set, epochs = 10)

Epoch 1/10
61/61 [==============================] - 44s 703ms/step - loss: 1.3840 - accuracy: 0.4078 - val_loss: 1.1321 - val_accuracy: 0.5000
Epoch 2/10
61/61 [==============================] - 23s 377ms/step - loss: 0.9874 - accuracy: 0.6111 - val_loss: 0.9066 - val_accuracy: 0.6415
Epoch 3/10
61/61 [==============================] - 23s 377ms/step - loss: 0.8100 - accuracy: 0.6850 - val_loss: 0.8085 - val_accuracy: 0.6792
Epoch 4/10
61/61 [==============================] - 23s 373ms/step - loss: 0.6718 - accuracy: 0.7347 - val_loss: 0.6651 - val_accuracy: 0.7170
Epoch 5/10
61/61 [==============================] - 23s 374ms/step - loss: 0.6353 - accuracy: 0.7396 - val_loss: 0.5184 - val_accuracy: 0.8113
Epoch 6/10
61/61 [==============================] - 23s 377ms/step - loss: 0.5415 - accuracy: 0.8040 - val_loss: 0.7545 - val_accuracy: 0.6981
Epoch 7/10
61/61 [==============================] - 23s 376ms/step - loss: 0.4779 - accuracy: 0.8131 - val_loss: 0.4840 - val_accuracy: 0.8208

Testing

In [18]:
test_image = image.load_img('../input/cotton-disease-dataset/Cotton Disease/test/fresh cotton leaf/d (7)_iaip.jpg',
                            target_size = (64,64))
test_image = image.img_to_array(test_image)
test_image=test_image/255
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)

In [19]:
result

array([[1.8242609e-02, 1.8994970e-04, 9.8153883e-01, 2.8667999e-05]],
      dtype=float32)

In [20]:
result = result.ravel()

In [21]:
result

array([1.8242609e-02, 1.8994970e-04, 9.8153883e-01, 2.8667999e-05],
      dtype=float32)

In [22]:
print("Largest element is:", max(result))

Largest element is: 0.98153883


In [23]:
result.sort
result 

array([1.8242609e-02, 1.8994970e-04, 9.8153883e-01, 2.8667999e-05],
      dtype=float32)

In [24]:
result=result.tolist() 

Conclusion

In [ ]:
result1=["diseased_leaf","diseased_plant","freash_leaf","freash_plant"]
max = result[0];    
     
#Loop through the array    
for i in range(0, len(result)):    
    #Compare elements of array with max    
    if(result[i] > max):    
        max = result[i];    
           
print("Largest element present in given array: " + str(max) +" And it belongs to " +str(result1[2]) +" class.");     